api_yamdb/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .views import (APIUserGetToken, APIUserSignup, CategoryViewSet,
                    CommentViewSet, GenreViewSet, ReviewViewSet, TitleViewSet,
                    UserViewSet, APIUserRemindConfirmationCode)

app_name = 'api-v1'

router_v1 = SimpleRouter()
router_v1.register(r'users', UserViewSet, basename='user')
router_v1.register(r'categories', CategoryViewSet, basename='category')
router_v1.register(r'genres', GenreViewSet, basename='genre')
router_v1.register(r'titles', TitleViewSet, basename='title')
router_v1.register(
    r'titles/(?P<title_id>\d+)/reviews', ReviewViewSet, basename='review'
)
router_v1.register(
    r'titles/(?P<title_id>\d+)/reviews/(?P<review_id>\d+)/comments',
    CommentViewSet, basename='comment'
)

urlpatterns = [
    path('v1/', include(router_v1.urls)),
    path('v1/auth/signup/', APIUserSignup.as_view()),
    path('v1/auth/token/', APIUserGetToken.as_view()),
    path('v1/auth/remind/', APIUserRemindConfirmationCode.as_view()),
]

api_yamdb/api_yamdb/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

handler404 = 'reviews.views.page_not_found'
handler500 = 'reviews.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redoc/', TemplateView.as_view(template_name='redoc.html'),
         name='redoc'),
    path('api/', include('api.urls', namespace='api-v1')),
    path('', include('reviews.urls', namespace='reviews')),
]

api_yamdb/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:titles>/', views.titles, name='titles'),
    path('<str:titles>/<int:title_id>/<int:reviews_id>/',
         views.review_view, name='review'),
    path('<str:titles>/<int:title_id>/<int:review_id>/edit/',
         views.review_edit, name="edit"),
]

api_yamdb/templates/misc/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    YaMDb
    © {% now 'Y' %}, все права защищены.
  </p>
</footer>

api_yamdb/templates/misc/nav.html
<nav class="navbar navbar-light" style="background-color: #a6f7a6;">
  <a class="navbar-brand" href="{% url 'reviews:index' %}">YaMDb</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    Пользователь:
    <a class="p-2 text-gray-dark" href="">{{ user.username }}</a>
    <a class="p-2 text-dark" href="">Новый отзыв</a>
    <a class="p-2 text-dark" href="">Изменить пароль</a>
    <a class="p-2 text-dark" href="">Выйти</a>
    {% else %}
    <a class="p-2 text-dark" href="">Войти</a> |
    <a class="p-2 text-dark" href="">Регистрация</a>
    {% endif %}
  </nav>
</nav>

api_yamdb/templates/misc/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; туда</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; туда</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">сюда &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">сюда &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}